### ISSUE TITLE
Internal Q&A - Samuel

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/portal#21]
# **Ask questions & document answers**
Each officer **must** ask 5 questions that they come up with when exploring the various codebases. Will be checked off once the answer to those questions has been documented. Codebases to review:
 - [portal](https://github.com/acmutd/portal)
 - [portal-backend](https://github.com/acmutd/portal-backend)
 - [Development](https://github.com/acmutd/Development)

Officer --> @Tegasaur  

### How to complete
Post questions as comments to this issue. Once comment receives a :+1: (will receive a thumbs up if there isn't already documentation surrounding the question) write the documentation for it & link it. That will result in the task list being checked off. Rinse and repeat 5 times. Ask as many questions as you have! :grin:

### **Q&A Checkoff Set 1**
- [x] Q1 & Documented
- [x] Q2 & Documented
- [ ] Q3 & Documented
- [ ] Q4 & Documented
- [ ] Q5 & Documented

**Comment by Tegasaur** [comment]
Question one: More like a confirmation. The acmAPI folder has an index file. I assume it holds all the functions to retrieve data from the backend. Is every endpoint function stored here? Also is there a reason it is called "index"?

**Comment by harshasrikara** [comment]
> Is every endpoint function stored here? Also is there a reason it is called "index"?

No real reason to call it index, we could have called it anything. Note: The goal behind creating the acmApi folder + associated helper files in there was to build a wrapper around api calls within our application. Essentially what we wanted to achieve was a situation where when we had to call the backend we would only have to specify the endpoint (for example `/auth0/profile` instead of the full URL. Then the helper functions in the acmApi folder would do things like the following:
 - Automatically insert authorization header
 - Automatically attach body (or additional parameters as needed)
 - Automatically unwrap the response data and return just the body

Important: This API wrapper was written quite some time back and during that time the backend changed significantly and therefore none of the UI components in the portal actually use the helper functions within the acmApi folder. Ideally one of our future goals is to refactor our code to use the the api wrapper to make it easier to work with our backend. 

**Review [the api folder](https://github.com/acmutd/portal/tree/dev/src/api) instead to see how we have all the functions setup to retrieve data from the backend**

Review this [pull request](https://github.com/acmutd/portal/pull/4) for more information on how things in the acmApi folder actually work. Remember that the code in that folder is not actually used anywhere in the application right now.

**Comment by Tegasaur** [comment]
This might be a bit broad but I really interested in learning about security and testing. My question is specifically for testing. How is sentry used in the frontend? Is there a general way to test every app of do you target specific errors? Thank you.

**Comment by Tegasaur** [comment]
Do we use only functional components strictly in react?

**Comment by harshasrikara** [comment]
> interested in learning about security and testing

This is a good place to read up about how the foundational layer for security & SSO is setup across various projects --> [ACM Zero Trust](https://docs.google.com/document/d/1EwdRjJWhr6ktnQcRLBeXfjXw5lp9SGbE7r8VJ-I7mLg/edit). Ofc its only a starter and there's much more that you'll learn / read about in various places throughout the code. 

Another good place to read is [here](https://github.com/acmutd/portal-backend/tree/dev/functions/src/express_configs) where we talk about how the various different endpoints in our API are secured in different ways.

> How is sentry used in the frontend? Is there a general way to test every app of do you target specific errors?

Sentry acts as one big catch-all for any errors that might happen at any point in the frontend. The setup process for sentry is in [index.tsx](https://github.com/acmutd/portal/blob/dev/src/index.tsx). Any issues that might happen get reported to Sentry and we can view them on the Sentry dashboard in a well organized fashion. Furthermore we also have it setup so that an errors will get posted to the `#sentry-feed` channel on slack for monitoring purposes.

One other place where we pass in additional data to Sentry besides `index.tsx` is in the [initialize.ts](https://github.com/acmutd/portal/blob/fa4be384be1fad6e8b644710e1540ae438273f50/src/api/actions/initialize.ts#L20) file which gets run when someone signs in to the portal. What we do here is basically add extra meta information to Sentry so that if errors happen it will also record the email of the person who was signed in when it happened. Very useful so that we can reach out to them to ask how the error happened / steps to reproduce. The whole Sentry setup process is a one time thing for the portal and there really isn't anything that requires changing.

**Comment by harshasrikara** [comment]
> Do we use only functional components strictly in react?

Yup 100% only functional components 💯

**Comment by Tegasaur** [comment]
The api folder does not seem to have a way to access all the routes in the backend (I didn't notice any axios calls). I feel like I am missing something. How does this folder help the app to access the backend.

**Comment by harshasrikara** [comment]
> The api folder does not seem to have a way to access all the routes in the backend

The `api` folder handles two things. These two things are called `state` and `actions`
 - State: Responsible for storing the global state of the application (using Recoil.js). This is in the [state.ts](https://github.com/acmutd/portal/blob/dev/src/api/state.ts) file. 
 - Actions: This is how the state gets populated with data from the backend/database. An action is essentially a script that makes the api call to fetch data, handle any errors/missing data and things of that nature. In our `state.ts` file for example one part of the state is `profile`. To populate that profile global state we have the script in [api/actions/profile.ts](https://github.com/acmutd/portal/blob/dev/src/api/actions/profile.ts). In this script you will find the axios calls to go fetch the data and then save it in our global state.

Note: There isn't an action to access every route in the backend. There are only API calls to the endpoints that we need. At a later point when we add new features that need new information we will add more actions to fetch the relevant data.

**Comment by Tegasaur** [comment]
You mentioned that the backend used for this project was serverless and yet somehow still a rest API. Can you expand on this?

**Comment by harshasrikara** [comment]
> You mentioned that the backend used for this project was serverless and yet somehow still a rest API.

Any API can be serverless. Whether its based on REST or SOAP or GraphQL or something else has no effect on whether it requires a server or is serverless. What it means for an API to be serverless is that there no continuously running VM or server provisioned 24/7 to handle requests.

Cloud functions (which is what firebase/gcp calls their serverless offering) automatically creates a server and loads up the backend when someone makes an API call. When no-one is using our REST API firebase will automatically switch off the servers so that they are not consuming any resources. This is pretty handy for us because it means we pay very little in fees because we're only billed when someone makes an API call because that's the only time that the server is provisioned and kept running.

Here's a good video to get a basic understanding of firebase cloud functions / serverless computing (from 1:00-5:00) [link](https://www.youtube.com/watch?v=udHm7I_OvJs)
Also take a look at Firebase Cloud Functions [use cases](https://firebase.google.com/docs/functions/use-cases)

**Comment by WillieCubed** [comment]
Closing since this is stale.
