### ISSUE TITLE
Internal Q&A - Steven

### ISSUE THREAD

**Issue by harshasrikara** [acmutd/portal#22]
# **Ask questions & document answers**
Each officer **must** ask 5 questions that they come up with when exploring the various codebases. Will be checked off once the answer to those questions has been documented. Codebases to review:
 - [portal](https://github.com/acmutd/portal)
 - [portal-backend](https://github.com/acmutd/portal-backend)
 - [Development](https://github.com/acmutd/Development)

Officer --> @Stevenmqnguyen 

### How to complete
Post questions as comments to this issue. Once comment receives a :+1: (will receive a thumbs up if there isn't already documentation surrounding the question) write the documentation for it & link it. That will result in the task list being checked off. Rinse and repeat 5 times. Ask as many questions as you have! :grin:

### **Q&A Checkoff Set 1**
- [ ] Q1 & Documented
- [ ] Q2 & Documented
- [ ] Q3 & Documented
- [ ] Q4 & Documented
- [ ] Q5 & Documented

**Comment by stevenmqnguyen** [comment]
How can I test portal-backend functions locally with and without affecting production firestore?

**Comment by harshasrikara** [comment]
> How can I test portal-backend functions locally with and without affecting production firestore?

Good question, in the main readme there's instruction about how to test the entire API locally. Running `npm run serve` will start local emulators for the cloud functions and firestore to ensure that any local testing doesn't tamper with the production DB. However, in order to test with the production DB, you'll need to only start the cloud functions emulator and not the firestore emulator. Thus, when the API goes to read/write data it would access the production DB. You can view more information about the various ways to setup local emulation options [here](https://firebase.google.com/docs/functions/local-emulator). 

The following command will only start the API but not start the local firestore emulation
```
$ firebase emulators:start --only functions
```

**Comment by stevenmqnguyen** [comment]
Closing - add contents to wiki.
